import {
  btnTexture,
  discordBtn,
  firstFooter,
  firstScreen,
  greenBtnSmall,
  greenBtn,
  screen2Smoke,
  screen5,
  logo,
} from "./imgs/webp";
import {
  firstScreenBack,
  scratchesDesktop,
  scratchesTablet,
  scratchesMobile,
} from "./imgs/webp/screen1";
import {
  FirstImg as screen2FirstImg,
  SecondImg as screen2SecondImg,
  ThirdImg as screen2ThirdImg,
  FourthImg as screen2FourthImg,
  MobileMask as screen2MobileMask,
} from "./imgs/webp/screen2";
import {
  FirstImg as screen3FirstImg,
  SecondImg as screen3SecondImg,
  ThirdImg as screen3ThirdImg,
  FourthImg as screen3FourthImg,
  FiveImg as screen3FiveImg,
  SixImg as screen3SixImg,
  HeaderTexture as screen3HeaderTexture,
} from "./imgs/webp/screen3";
import {
  FirstImg as screen4FirstImg,
  SecondImg as screen4SecondImg,
  ThirdImg as screen4ThirdImg,
  Mask as screen4Mask,
  SmokeMobile as screen4SmokeMobile,
  MaskTablet as screen4MaskTablet,
  MaskMobile as screen4MaskMobile,
} from "./imgs/webp/screen4";
import { Plane, GoodPoint, BadPoint } from "./imgs/webp/screen6";
import {
  Photo1,
  Photo2,
  Photo3,
  RedRiftLogo,
  WebLink,
  SmokeMobile,
  Alex,
  Cris,
  Dasha,
  Egor,
  Hanna,
  Katsia,
  Maya,
  Mike,
  Nastia,
  Pasha,
  Veronika,
  Gary,
  LinkedIn,
} from "./imgs/webp/screen7";
import {
  Partner1,
  Partner2,
  Partner3,
  Partner4,
  Partner1Color,
  Partner2Color,
  Partner3Color,
  Partner4Color,
} from "./imgs/webp/screen8";
import {
  Linked,
  Discord,
  Medium,
  TikTok,
  Tg,
  Twitter,
  Logo,
  Scratches,
  ScratchesMobile,
} from "./imgs/webp/screen9";
import { Texture, Solana, Damnn } from "./imgs/webp/screen10";
import { monkeyWebM, monkeyMp4, PreLogoWebM, PreLogoMp4 } from "./videos";
import Smoke from "./imgs/smoke2x.png";

const getAllImage = () => {
  return [
    btnTexture,
    discordBtn,
    firstFooter,
    firstScreen,
    greenBtnSmall,
    greenBtn,
    screen2Smoke,
    screen5,
    logo,
    firstScreenBack,
    scratchesDesktop,
    scratchesTablet,
    scratchesMobile,
    screen2FirstImg,
    screen2SecondImg,
    screen2ThirdImg,
    screen2FourthImg,
    screen2MobileMask,
    screen3FirstImg,
    screen3SecondImg,
    screen3ThirdImg,
    screen3FourthImg,
    screen3FiveImg,
    screen3SixImg,
    screen3HeaderTexture,
    screen4FirstImg,
    screen4SecondImg,
    screen4ThirdImg,
    screen4Mask,
    screen4SmokeMobile,
    screen4MaskTablet,
    screen4MaskMobile,
    Plane,
    GoodPoint,
    BadPoint,
    Photo1,
    Photo2,
    Photo3,
    RedRiftLogo,
    WebLink,
    Smoke,
    SmokeMobile,
    Partner1,
    Partner2,
    Partner3,
    Partner4,
    Partner1Color,
    Partner2Color,
    Partner3Color,
    Partner4Color,
    Linked,
    Discord,
    Medium,
    TikTok,
    Tg,
    Twitter,
    Logo,
    Scratches,
    ScratchesMobile,
    Texture,
    Solana,
    Damnn,
    Alex,
    Cris,
    Dasha,
    Egor,
    Hanna,
    Katsia,
    Maya,
    Mike,
    Nastia,
    Pasha,
    Veronika,
    Gary,
    LinkedIn,
  ];
};
const getAllVideo = () => {
  return [monkeyMp4, PreLogoMp4];
};

export { getAllImage, getAllVideo };
